### ISSUE TITLE
Cannot find module 'FirebaseAdmin' 

### ISSUE THREAD

**Issue by budasuyasa** [Perafan18/adonis-firebase-admin#1]
- Firebase Provider Version: #.#.# (`npm list --depth=0`):
+-- @adonisjs/ace@5.0.8
+-- @adonisjs/auth@3.0.7
+-- @adonisjs/bodyparser@2.0.9
+-- @adonisjs/cors@1.0.7
+-- @adonisjs/fold@4.0.9
+-- @adonisjs/framework@5.0.12
+-- @adonisjs/ignitor@2.0.8
+-- @adonisjs/lucid@6.1.3
+-- @adonisjs/session@1.0.28
+-- @adonisjs/shield@1.0.8
+-- @adonisjs/validator@5.0.6
+-- adonis-firebase-admin@1.1.2
+-- firebase-admin@6.2.0
`-- mysql@2.16.0
- Node Version (`node -v`): v8.10.0
- NPM Version (`npm -v`): 5.6.0
- OS: Windows 10 Pro

### Description:
So I try to include this module in my  controller using: 
`const FirebaseAdmin = use('FirebaseAdmin') `
Before that, I also added this on `providers` array : 
```
'adonis-firebase-admin/providers/Firebase',
'adonis-firebase-admin/providers/FirebaseAdmin'
```

And i got *Cannot find module 'FirebaseAdmin'*. Im I missing something?

**Comment by jhorlima** [comment]
use 
`const FirebaseAdmin = use('Perafan/FirebaseAdmin');`
